# Applications
cask "rectangle-pro"
cask "jetbrains-toolbox"
cask "blender"
cask "openscad@snapshot"
cask "mountain-duck"

# CLI tools
brew "tmux"
brew "pulumi"
brew "fluxcd/tap/flux"
brew "loft-sh/tap/vcluster"
brew "xcodes"
brew "xcodegen"
brew "ansible"
brew "k9s"
brew "imagemagick"
brew "getsentry/tools/sentry-cli"
brew "siderolabs/tap/talosctl"
brew "talhelper"
brew "sops"
brew "age"
brew "yq"
